- name: Copy Galaxy configuration files
  copy:
      src: ../w4m-config/config/
      dest: "{{ galaxy_config_dir }}"
  
- name: Copy Galaxy static files
  copy:
      src: ../w4m-config/static/
      dest: "{{ galaxy_server_dir }}/static"
 
- name: Install Galaxy systemd service script
  copy:
      src: ../galaxy.service
      dest: "/etc/systemd/system"
      mode: "a+r"
  become: yes
  
- name: Enable Galaxy systemd service
  systemd:
      name: galaxy.service
      enabled: yes
  become: yes
