- hosts: w4mdev-azerty w4mprod-azerty
  roles:
      - azerty

- hosts: all
  vars:
    galaxy_server_dir: "/home/vagrant/galaxy"
    galaxy_config_dir: "{{ galaxy_server_dir }}/config"
    galaxy_mutable_config_dir: "{{ galaxy_config_dir }}"
    galaxy_vcs: git
    galaxy_fetch_dependencies: yes
    galaxy_fetch_eggs: yes
    galaxy_manage_static_setup: yes
    galaxy_manage_mutable_setup: no
    galaxy_manage_database: yes
    galaxy_changeset_id: release_18.09
    galaxy_force_checkout: yes
    galaxy_config:
      "server:main":
        "host": "0.0.0.0"
      "app:main":
        job_working_directory: "{{ galaxy_config_dir }}/job_working_directory"
        tool_config_file: "{{ galaxy_config_dir }}/tool_conf.xml,{{ galaxy_shed_tool_conf_file }}"
        tool_sheds_config_file: "{{ galaxy_config_dir }}/tool_sheds_conf.xml"
        master_api_key: "admin"
#        tool_dependency_dir: "/deps"
        admin_users: "admin@w4m.org"
        conda_auto_init: True
        conda_auto_install: True
        dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"
  roles:
    - prerequisites
    - galaxy
    - galaxy-config
  tasks:
      - name: Enable and start Galaxy service
        command: "systemctl --user enable --now galaxy.service"
